services:
  - docker

matrix:
  include:
    - os: linux
      dist: trusty

language: node_js

node_js:
  - "8"

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

jobs:
  include:
    - stage: 8.6.0 - 1.14.2
      script:
        - docker build -t $DOCKER_REPO:8.6.0 8.6.0
        - docker tag $DOCKER_REPO:8.6.0 $DOCKER_REPO:8.6.0
        - docker push $DOCKER_REPO:8.6.0
    - stage: latest
      script:
        - docker build -t $DOCKER_REPO:latest 8.6.0
        - docker tag $DOCKER_REPO:latest $DOCKER_REPO:latest
        - docker push $DOCKER_REPO
    - stage: deploy
      script:
        - docker pull $DOCKER_REPO
